services:
  postgres:
    container_name: postgres
    image: postgres:14.15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./docker/volume/postgres/data:/var/lib/postgresql/data
